name: zenith_web
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  rexios_lints: ^1.0.0
  flutter_launcher_icons_maker: ^0.10.2

flutter:
  uses-material-design: true

# flutter pub run flutter_launcher_icons_maker:main
flutter_icons:
  web: true
  image_path: "assets/icon/icon.png"